version: "3.0"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379




